### ISSUE TITLE
Arrange everything into seperate folders and managing the structure & UI Improvements

### ISSUE THREAD

**Issue by Smitkhobragade** [tinkten7/farmbuddy2023#1]
Pls assign me this issue.

**Comment by tinkten7** [comment]
You continue with the issue

**Comment by tinkten7** [comment]
You can go ahead and create the folders.

**Comment by Smitkhobragade** [comment]
Can you pls assign it on github and put hactoberfest label

**Comment by tinkten7** [comment]
ok i have put a label
