### ISSUE TITLE
Bug in signin/signup 

### ISSUE THREAD

**Issue by p-sai-gowtham** [tinkten7/farmbuddy2023#3]
there is a bug in signin/signup connectivity i can solve it

**Comment by tinkten7** [comment]
Yess...go with that

**Comment by p-sai-gowtham** [comment]
plz provide me the hacktoberfest label

**Comment by p-sai-gowtham** [comment]
ok

**Comment by p-sai-gowtham** [comment]
issue has been resolved

**Comment by tinkten7** [comment]
thanks for your contribution
