### ISSUE TITLE
Security Update 🔐

### ISSUE THREAD

**Issue by sahilhedau49** [tinkten7/farmbuddy2023#5]
1. As I can see in your index.html file there is firebase config details which is very sensitive for any project and it is like a unique key for your firebase console. 

2. In your cart section after removing all products, cart price is not going 0.

**Comment by sahilhedau49** [comment]
I want to fix this problems. I will add it in env file and will update .gitignore file too.

**Comment by tinkten7** [comment]
Proceed with what you can do

**Comment by tinkten7** [comment]
Fix my issue

**Comment by tinkten7** [comment]
What's the update on issue

**Comment by sahilhedau49** [comment]
Done

**Comment by tinkten7** [comment]
thank you for your contribution
